[server]
    port = "3005"
    imagePath = "./images"
    host = "http://localhost:3005"

[postgres]
    user = "postgres"
    password = "HelloDong123@"
    host = "localhost"
    port = "5433"
    dbname = "pictures"
